language: go
os: linux
dist: xenial

env:
  global:
    - upstream="armPelionEdge/maestro"


# go's 'opinions' can die in a fire...
install:
  - |
    cd ../../
    mkdir "$(dirname "${upstream}")"
    mv "${TRAVIS_REPO_SLUG}" "${upstream}"
    cd "${upstream}"


script: 
  # Build dependencies
  - ./build-deps.sh

  # Build maestro
  - ./build.sh

  # Run unit tests
  - go test "github.com/${upstream}" || true


matrix:
  include:

    - name: "go v1.10"
      go: 1.10.x

    - name: "go v1.11"
      go: 1.11.x

    - name: "go v1.12"
      go: 1.12.x


