language: go
os: linux
dist: xenial

env:
  global:
    - fork_src="armPelionEdge/maestro"


# go's 'opinions' can die in a fire...
install:
  - |
    cd ../../
    mkdir "$(dirname "${fork_src}")"
    mv -v "${TRAVIS_REPO_SLUG}" "${fork_src}"
    cd "${fork_src}"


script: 
  - pwd
  - ls -al
  # Build dependencies
  - ./build-deps.sh

  # Build maestro
  - ./build.sh

  # Run unit tests
  - go test "github.com/${fork_src}" || true


matrix:
  include:

    - name: "go v1.10"
      go: 1.10.x

    - name: "go v1.11"
      go: 1.11.x

    - name: "go v1.12"
      go: 1.12.x


