language: go
os: linux
dist: xenial

env:
  global:
    - upstream="armPelionEdge/maestro"


install:
  # Moves a fork to the upstream directory, because of go's _opinions_...
  - |
    if [[ "${TRAVIS_REPO_SLUG}" != "${upstream}" ]]; then
      cd ../../
      mkdir -p "${upstream}"
      mv -v "${TRAVIS_REPO_SLUG}/" "${upstream}"
      cd "${upstream}"
    fi


script: 
  # Build dependencies
  - ./build-deps.sh

  # Build maestro
  - ./build.sh

  # Run unit tests
  - go test "github.com/${upstream}" || true


matrix:
  include:

    - name: "go v1.10"
      go: 1.10.x

    - name: "go v1.11"
      go: 1.11.x

    - name: "go v1.12"
      go: 1.12.x


