language: go
os: linux
dist: xenial

env:
  global:
    - parent_user="armPelionEdge"
    - parent_repo="maestro"


# Note: This repo has an unmaintained 'GoDep' index.  Bypassing for now.
#       https://docs.travis-ci.com/user/languages/go/#godep-support
install:
  - mkdir "../../${parent_user}"
  - ln -s "$(pwd)" "$(readlink -m "../../${parent_user}/${parent_repo}")"
  - ls -al ../../*/*

script: 
  # Build dependencies
  - ./build-deps.sh

  # Build maestro
  - ./build.sh

  # Run unit tests
  - go test "github.com/${TRAVIS_REPO_SLUG}" || true


matrix:
  include:

    - name: "go v1.10"
      go: 1.10.x

    - name: "go v1.11"
      go: 1.11.x

    - name: "go v1.12"
      go: 1.12.x


